# Generated by Django 5.0.7 on 2024-07-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastorder',
            options={'ordering': ['created_at'], 'verbose_name': 'Запрос прогноза', 'verbose_name_plural': 'Запросы прогноза'},
        ),
        migrations.AddField(
            model_name='forecastorder',
            name='city_lat',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='forecastorder',
            name='city_lon',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
    ]
