# Generated by Django 5.0.7 on 2024-07-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_alter_forecastorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastorder',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время запроса'),
        ),
    ]
