# Generated by Django 5.0.7 on 2024-07-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_alter_forecastorder_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос прогноза', 'verbose_name_plural': 'Запросы прогноза'},
        ),
    ]
